# fly.toml app configuration file generated for brewdog-basket on 2023-11-05T11:54:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brewdog-basket"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
